install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7"; fi
  
  # Info about Compiler
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
  - python --version

  # Info about OS
  - uname -a
  - echo $TRAVIS_OS_NAME

  # Homebrew (Mac OSX)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install eigen python boost-python; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/bin:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pip install numpy matplotlib; fi
  
# APT (Linux)
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      #- llvm-toolchain-precise-3.7
      - boost-latest
    packages:
      - gcc-4.9
      - g++-4.9
      #- clang-3.7
      - cmake
      - libboost1.54-all-dev
      - libboost-python1.54-dev
      - libeigen3-dev
      - python-dev
      - python-numpy

os:
  - linux
  - osx
  
env:
  - CONFIG=Release
  - CONFIG=Debug

language: cpp

compiler:
  - clang
  - gcc
  
matrix:
  exclude:
    # OSX boost is compiled with Clang (skip gcc builds)
    - os: osx
      compiler: gcc
      env: CONFIG=Release
      
    - os: osx
      compiler: gcc
      env: CONFIG=Debug
      
    # LLVM repos are down
    - os: linux
      compiler: clang
      env: CONFIG=Release
      
    - os: linux
      compiler: clang
      env: CONFIG=Debug

before_script:
  - mkdir build
  - pushd $(pwd)
  - cd build

  # Build Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake ../ -DISEN_PYTHON=ON -DCMAKE_BUILD_TYPE=$CONFIG; fi
  
  # Build OSX (use homebrew python)
  - export OSX_PYTHON_INCLUDE="$(python-config --prefix)/include/python2.7"
  - export OSX_PYTHON_LIBRARY="$(python-config --prefix)/lib/libpython2.7.dylib"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake ../ -DISEN_PYTHON=ON -DCMAKE_BUILD_TYPE=$CONFIG -DPYTHON_INCLUDE_DIR="${OSX_PYTHON_INCLUDE}" -DPYTHON_LIBRARY="${OSX_PYTHON_LIBRARY}"; fi
  
  # Build & Install
  - make
  - make install
  
  - popd

script:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd bin/Linux; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd bin/Darwin/; fi
   
   # Run C++ unittests
   - ./isen_test

   # Run Python unittests
   - cd python
   - python isen_test.py
   
notifications:
  email:
    recipients:
      - fabian_thuering@hotmail.com
    on_success: never
    on_failure: always
    
sudo: false

