install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7"; fi
  
  # Info about Compiler
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
  - python --version

  # Info about OS
  - uname -a
  - echo $TRAVIS_OS_NAME

  # Install OSX (boost and cmake already installed)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install eigen; fi
  
  - brew info python
  - brew info boost

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - boost-latest
    packages:
      - gcc-4.9
      - g++-4.9
      - clang-3.7
      - cmake
      - libboost1.54-all-dev
      - libboost-python1.54-dev
      - libeigen3-dev
      - python-dev
      - python-numpy

os:
#  - linux
  - osx
  
env:
#  - CONFIG=Release
  - CONFIG=Debug

language: cpp

compiler:
  - clang
  - gcc
  
matrix:
  exclude:
    # OSX boost is compiled with Clang (skip gcc builds)
    - os: osx
      compiler: gcc
      env: CONFIG=Release
      
    - os: osx
      compiler: gcc
      env: CONFIG=Debug

before_script:
  - mkdir build
  - pushd $(pwd)
  - cd build

  # Build Linux (with Python)
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake ../ -DISEN_PYTHON=ON -DCMAKE_BUILD_TYPE=$CONFIG; fi
  
  # Build OSX (without Python)
  
  - export OSX_PYTHON_INCLUDE="$(python-config --includes | sed 's/^..//')"
  - export OSX_PYTHON_LIBRARY="$(python-config --prefix)/lib/libpython2.7.dylib"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake ../ -DISEN_PYTHON=ON -DPYTHON_INCLUDE_DIR=${OSX_PYTHON_INCLUDE} -DPYTHON_LIBRARY=${OSX_PYTHON_LIBRARY} -DCMAKE_BUILD_TYPE=$CONFIG; fi
  
  # Build & Install
  - make
  - make install
  
  - popd

script:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd bin/Linux; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd bin/Darwin/; fi
   
   # Run C++ unittests
   - ./isen_test

   # Run Python unittests
   
notifications:
  email:
    recipients:
      - fabian_thuering@hotmail.com
    on_success: never
    on_failure: always
    
sudo: false

