branches:
  only:
    - master
    
platform: 
    - x64

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Debug
      
init:
  - cmd: cmake --version

build_script:
  - cmd: cmake "-G%GENERATOR%" -H. -Bbuild
  - cmd: cmake --build build --config "%CONFIG%"
  
test_script:
  - ps: cd build
  # - ctest -VV -C "%CONFIG%"