  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

branches:
  only:
    - master
    
platform: 
    - x64

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Debug

init:
    - cmd: cmake --version

build_script:
    # Setup Eigen3
    # ------------
    - ps: git clone -q --branch=master https://github.com/RLovelett/eigen.git C:\projects\isen\ext\eigen3
    
    # Setup Boost
    # -----------
    - cmd: set "BOOST_ROOT=C:\Libraries\boost_1_60_0"
    
    # Setup Python (Numpy)
    # -------------------
    - cmd: C:\Python27\Scripts\pip.exe install numpy
    
    # Build
    - cmd: cmake "-G%GENERATOR%" -H. -Bbuild -DISEN_PYTHON=ON
    - cmd: cmake --build build --config "%CONFIG%"

test_script:
  - ps: cd build
  # - ctest -VV -C "%CONFIG%"