branches:
  only:
    - master
    
platform: 
    - x64

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release
      PYTHON_ENABLE: ON
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Debug
      PYTHON_ENABLE: ON
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release
      PYTHON_ENABLE: OFF
    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Debug
      PYTHON_ENABLE: OFF

init:
    - cmd: cmake --version

build_script:
    # Setup Eigen3
    # ------------
    - ps: git clone -q --branch=master https://github.com/RLovelett/eigen.git C:\projects\isen\ext\eigen3
    
    # Setup Python (Numpy)
    # --------------------
    - cmd: set "PYTHON_INCLUDE_DIR=C:\Python27-x64\include"
    - cmd: set "PYTHON_LIBRARY=C:\Python27-x64\libs"
    - cmd: set "PYTHON_EXECUTABLE=C:\Python27-x64\python.exe"
    
    - cmd: C:\Python27-x64\Scripts\pip.exe install numpy
    
    # Setup Boost
    # -----------
    - cmd: set "BOOST_ROOT=C:\Libraries\boost_1_60_0"
    - cmd: set "BOOST_LIBRARYDIR=C:\Libraries\boost_1_60_0\lib64-msvc-14.0"
    
    # Build & install
    - cmd: cmake "-G%GENERATOR%" -H. -Bbuild -DISEN_PYTHON="%PYTHON_ENABLE%" -DBoost_USE_STATIC_LIBS="ON" -DPYTHON_EXECUTABLE="%PYTHON_EXECUTABLE%"
    - cmd: cmake --build build --config "%CONFIG%"
    - cmd: cmake --build build --config "%CONFIG%" --target INSTALL

test_script:
  - cmd: cd bin\Windows
  - cmd: PATH %PATH%;%BOOST_LIBRARYDIR%
  - cmd: PATH %PATH%;%PYTHON_LIBRARY%
  
  # C++ tests
  # -----------
  - cmd: .\isen_test.exe
  
  # Python tests
  # -----------
  - cmd: if [%PYTHON_ENABLE%]==[ON] cd python
  - cmd: if [%PYTHON_ENABLE%]==[ON] %PYTHON_EXECUTABLE% isen_test.py
